version: '3.8'

services:
  mariadb:
    image: mariadb:11.3
    container_name: mariadb11-board
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: board
      MARIADB_USER: root
      MARIADB_PASSWORD: root
    ports:
      - "43306:3306"
    volumes:
      - mariadb_board_data:/var/lib/mysql
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --lower_case_table_names=0
  redis:
    image: redis:7-alpine
    container_name: redis-board
    restart: always
    ports:
      - "46379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_board_data:/data

volumes:
  mariadb_board_data:
  redis_board_data: